"""task_lists

Revision ID: 0002_task_lists
Revises: 0001_users
Create Date: 2026-10-08

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002_task_lists"
down_revision: Union[str, None] = "0001_users"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "task_lists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_task_lists_name_not_blank"
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name="fk_task_lists_owner_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_task_lists"),
    )
    # Not autogenerated: a functional unique index over `lower(name)` is
    # written by hand (design ADR-08/ADR-10), mirrored in
    # `db/models.py` as a standalone `Index(..., func.lower(...))` next to
    # `TaskListModel`.
    op.create_index(
        "uq_task_lists_owner_id_lower_name",
        "task_lists",
        ["owner_id", sa.text("lower(name)")],
        unique=True,
    )
    op.create_index(
        op.f("ix_task_lists_owner_id"), "task_lists", ["owner_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_task_lists_owner_id"), table_name="task_lists")
    op.drop_index("uq_task_lists_owner_id_lower_name", table_name="task_lists")
    op.drop_table("task_lists")
